taybct:
  wechat:
    # 应用唯一标识，在微信开放平台提交应用审核通过后获得
    app-id: wx458a0f41469235b2
    # 应用密钥AppSecret，在微信开放平台提交应用审核通过后获得
    app-secret: eed1b78b9bf2255375a313074e609afa
    # 重定向地址，需要进行UrlEncode
    redirect-url: http://3tcj7j.natappfree.cc/api/wx/token
    # 登录成功的页面
#    login-success-page: http://www.baidu.com