swagger:
  title: "业务模块"
  description: "管理基础的功能"
  version: 3.0.0
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'default'
      display-name: ${swagger.title}
      paths-to-match: '/**'
      packages-to-scan:
        - io.github.mangocrisp.spring.taybct
  show-actuator: false
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    # Knife4j默认显示中文(zh-CN),如果开发者想直接显示英文(en-US)，在通过该配置进行设置即可
    language: zh_cn
    # 开启动态请求参数，true-开启，false-关闭
    enable-dynamic-parameter: true
    # 是否开启界面中对某接口的版本控制,如果开启，后端变化后Ui界面会存在小蓝点
    enable-version: true
    # 是否在每个Debug调试栏后显示刷新变量按钮,默认不显示
    enable-reload-cache-parameter: true
  # 开启生产环境屏蔽
  production: false